version: "3"

services:
    # Serviço Web
    customerapp-nginx:
        image: nginx:1.13
        container_name: customer-nginx
        volumes:
            - "${APP_PATH}:/var/www/html"
            - "${NGINX_PATH}:/etc/nginx/nginx.conf"
        ports:
            - "${NGINX_PORT}:80"
        depends_on:
            - customerapp-app

    # Serviço PHP
    customerapp-app:
        build:
            context: ${PHP_PATH}
        container_name: customer-app
        volumes:
            - "${APP_PATH}:/var/www/html"
        ports:
            - "${PHP_PORT}:9000"
        depends_on:
            - customerapp-mysql
        environment:
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASS=${MYSQL_PASS}

    # Serviço MySql
    customerapp-mysql:
        image: mysql:5.7.20
        container_name: customer-mysql
        volumes:
            - "db_data_customer:/var/lib/mysql"
        ports:
            - "${MYSQL_PORT}:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

networks:
    default:
        external:
            name: microservices

volumes:
    db_data_customer: